### ISSUE TITLE
Failsafe fails to run on linux

### ISSUE THREAD

**Issue by bvklingeren** [jan-molak/npm-failsafe#1]
**Errormessage:**
```
/usr/bin/env: node --harmony: No such file or directory
```

**Reproduction path:**
```
$ yarn run jenkins:e2e
```
Command was run by a linux docker container.

**Context:**
Excerpt scripts section in package.json:
```
    "jenkins:e2e": "failsafe e2e:run e2e:report",
    "e2e:run": "ng e2e",
    "e2e:report": "node scripts/e2e-html-report.js",
```

**Fix pointer:**
When searching for an explanation I found [this report](https://bbs.archlinux.org/viewtopic.php?pid=1313972#p1313972) and I think it's in the failsafe script in the bin directory.

**Comment by jan-molak** [comment]
Hey and thanks for reporting the issue, I should be able to look into this within the next week. In the meantime pull requests would be much appreciated!

**Comment by bvklingeren** [comment]
Hi Jan, a pull request seems fair, but I don't know the reason of your decision to have a 'binary' script with the `#!/usr/bin/node --harmony` shebang. Could you elaborate on that?

**Comment by jan-molak** [comment]
Hey Boudewijn, I've used the `#!/usr/bin/env node --harmony` switch to enable some of the es6 features,  such as the [`let` variable declaration](http://node.green/#let) and the [spread operator](http://node.green/#spread-------operator) support on older versions of node.js. 

We could pull it out I suppose as long as the minimum version of node.js required to run the module is 5.11.x I think. Not sure how many people are still using node 4.x on their projects though?

**Comment by jan-molak** [comment]
I've bumped the required version of node to 5.11.x and removed the `--harmony` switch. Please let me know if this solves the problem for you.

I'm happy to add a separate node 4.x-specific script or replace the es6-specific features with es5 equivalents if there's a need for that.

Best,
Jan

**Comment by bvklingeren** [comment]
Hi Jan, thanks for the update and fix. Failsafe works correctly now in my situation.

Regarding the required node version, I have no objection against the requirement to use 5.11.x or higher. If I were you, I'd wait for the moment that someone requested to have a version working for previous versions of node. And even then, an upgrade of node should be considered first, since there are lots of unnecessary old installations of node lying around for no reason ;-)

**Comment by jan-molak** [comment]
Glad to hear that the fix helped! Yeah, that's pretty much the approach I've decided to take ;-) There's no reason to support old versions of node if no one is using them.
