### ISSUE TITLE
--harmony: Linux kernel does not accept multiple shebang arguments

### ISSUE THREAD

**Issue by san-ouadghiri** [jan-molak/npm-failsafe#6]
Hi !

**Env.**
Ubuntu 16.04 (but applies to all Linux/Cygwin kernel it seems [1])

**Problem**
Linux does not allow multiple arguments after a shebang. As a consequence, lines such as...
`#!/usr/bin/env node --harmony`

causes
```
> failsafe e2e report
/usr/bin/env: «node --harmony»: Aucun fichier ou dossier de ce type
//meaning No files or folder of such a type found
```
**Notes**
A simple "fix" is to remove --harmony under npm-failsafe > bin > failsafe, shebang line. This is what is advised on another project [2bis] as it would be less relevant today. If important though, it seems that a workaround is possible [3].

I let you consider and see if that make sense for your project to fix this or not. On my side, I removed the --harmony in the meanwhile to be able to move on :).

*References*
[1] https://github.com/smikes/node/blob/minus-x-switch/doc/Minus-X-Switch-Proposal.md#shebang-interpretation
[2] Other project, same issue - https://github.com/SpencerCDixon/redux-cli/issues/42
[2bis] And https://github.com/SpencerCDixon/redux-cli/issues/42#issuecomment-192755325
[3] Workaround - http://sambal.org/2014/02/passing-options-node-shebang-line/

**Comment by jan-molak** [comment]
Thanks Hi @san-ouadghiri and thanks for reporting that. Could you please advise what version of `npm-failsafe` are you using? The current one no longer has the `--harmony` flag as it's been [removed in November 2016](https://github.com/jan-molak/npm-failsafe/commit/58fc820b67783661ad4bba96d26a3b8f9b449a00).

Jan

**Comment by san-ouadghiri** [comment]
Hi,

My bad indeed, I was using ^0.1.0. I think I got that from https://github.com/jan-molak/serenity-js/blob/master/examples/todomvc-protractor-mocha/package.json. I certainly missed the fact that the list may not be updated; I should have consider that. 

Thanks for the kind reply ; now I'm targeting ^0.4.1.

**Comment by jan-molak** [comment]
Ah, excellent point, thank you! I'll update the examples.
